cmake_minimum_required(VERSION 3.19)

foreach(required SOURCE_ROOT INVENTORY STAGE EXPECTED_SOURCE_COUNT VERIFY_ONLY)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "Missing ${required}")
    endif()
endforeach()
if(NOT VERIFY_ONLY)
    message(FATAL_ERROR "Pruning inventory is verification only")
endif()
foreach(forbidden CAPTURE_MODE UPDATE_MODE WRITE_EXPECTED)
    if(DEFINED ${forbidden})
        message(FATAL_ERROR "${forbidden} is not supported")
    endif()
endforeach()

set(root_hint "${CMAKE_CURRENT_LIST_DIR}/../..")
file(REAL_PATH "${SOURCE_ROOT}" source_root BASE_DIRECTORY "${root_hint}")
file(REAL_PATH "${INVENTORY}" inventory_path BASE_DIRECTORY "${root_hint}")
file(READ "${inventory_path}" inventory)

string(JSON schema ERROR_VARIABLE json_error GET "${inventory}" schemaVersion)
if(json_error OR NOT schema EQUAL 1)
    message(FATAL_ERROR "Unsupported pruning inventory schema")
endif()
string(JSON gate GET "${inventory}" gateId)
if(NOT gate STREQUAL "NO_ETA_HEURISTIC_PRUNING_AUDIT")
    message(FATAL_ERROR "Unexpected pruning gate")
endif()

file(GLOB_RECURSE actual_sources
    RELATIVE "${source_root}"
    "${source_root}/ai/coordinator/*.cpp"
    "${source_root}/ai/coordinator/*.h")
list(APPEND actual_sources ai/coordinatedai.cpp ai/coordinatedai.h)
list(REMOVE_DUPLICATES actual_sources)
list(SORT actual_sources)
list(LENGTH actual_sources actual_count)
if(NOT actual_count EQUAL EXPECTED_SOURCE_COUNT)
    message(FATAL_ERROR "Production source count is ${actual_count}, expected ${EXPECTED_SOURCE_COUNT}")
endif()

string(JOIN "\n" source_derivation ${actual_sources})
string(SHA256 source_derivation_hash "${source_derivation}")
string(JSON expected_derivation GET "${inventory}" sourceSetDerivationSha256)
if(NOT source_derivation_hash STREQUAL expected_derivation)
    message(FATAL_ERROR "Production source closure changed")
endif()

string(JSON snapshot_count LENGTH "${inventory}" stageSnapshots)
set(snapshot_index -1)
if(snapshot_count GREATER 0)
    math(EXPR snapshot_last "${snapshot_count} - 1")
    foreach(index RANGE 0 ${snapshot_last})
        string(JSON snapshot_stage GET "${inventory}" stageSnapshots ${index} stage)
        if(snapshot_stage STREQUAL STAGE)
            set(snapshot_index ${index})
        endif()
    endforeach()
endif()
if(snapshot_index LESS 0)
    message(FATAL_ERROR "Missing ${STAGE} pruning snapshot")
endif()

string(JSON source_count LENGTH "${inventory}" stageSnapshots ${snapshot_index} sources)
if(NOT source_count EQUAL EXPECTED_SOURCE_COUNT)
    message(FATAL_ERROR "Snapshot source count is ${source_count}, expected ${EXPECTED_SOURCE_COUNT}")
endif()
math(EXPR source_last "${source_count} - 1")
foreach(index RANGE 0 ${source_last})
    string(JSON expected_path GET "${inventory}" stageSnapshots ${snapshot_index} sources ${index} path)
    string(JSON expected_hash GET "${inventory}" stageSnapshots ${snapshot_index} sources ${index} sha256)
    list(GET actual_sources ${index} actual_path)
    if(NOT expected_path STREQUAL actual_path)
        message(FATAL_ERROR "Source mismatch at ${index}: ${expected_path} versus ${actual_path}")
    endif()
    if(IS_DIRECTORY "${source_root}/${actual_path}" OR IS_SYMLINK "${source_root}/${actual_path}")
        message(FATAL_ERROR "Source is not a regular file: ${actual_path}")
    endif()
    file(SHA256 "${source_root}/${actual_path}" actual_hash)
    if(NOT actual_hash STREQUAL expected_hash)
        message(FATAL_ERROR "Source hash mismatch: ${actual_path}")
    endif()
endforeach()

set(allowed_classes
    EXACT_FEASIBILITY
    EXACT_HORIZON_ZERO
    EXACT_DOMINANCE
    ADMISSIBLE_BOUND
    SAFE_INTERVAL
    EXACT_CERTIFICATE
    FROZEN_COUNT_TRUNCATION
    FIXED_POINT_STOP
    FAIL_CLOSED_FALLBACK)
string(JSON operation_count LENGTH "${inventory}" stageSnapshots ${snapshot_index} operations)
if(operation_count LESS 1)
    message(FATAL_ERROR "Pruning operation inventory is empty")
endif()
math(EXPR operation_last "${operation_count} - 1")
set(operation_ids)
foreach(index RANGE 0 ${operation_last})
    string(JSON operation_id GET "${inventory}" stageSnapshots ${snapshot_index} operations ${index} id)
    string(JSON operation_path GET "${inventory}" stageSnapshots ${snapshot_index} operations ${index} path)
    string(JSON operation_class GET "${inventory}" stageSnapshots ${snapshot_index} operations ${index} allowedClass)
    string(JSON test_count LENGTH "${inventory}" stageSnapshots ${snapshot_index} operations ${index} supportingTests)
    list(FIND operation_ids "${operation_id}" duplicate_index)
    list(FIND actual_sources "${operation_path}" source_index)
    list(FIND allowed_classes "${operation_class}" class_index)
    if(NOT duplicate_index EQUAL -1)
        message(FATAL_ERROR "Duplicate pruning operation: ${operation_id}")
    endif()
    if(source_index EQUAL -1)
        message(FATAL_ERROR "Unknown operation source: ${operation_path}")
    endif()
    if(class_index EQUAL -1)
        message(FATAL_ERROR "Unknown pruning class: ${operation_class}")
    endif()
    if(test_count LESS 1)
        message(FATAL_ERROR "Operation lacks proof coverage: ${operation_id}")
    endif()
    list(APPEND operation_ids "${operation_id}")
endforeach()
set(sorted_operation_ids ${operation_ids})
list(SORT sorted_operation_ids)
if(NOT operation_ids STREQUAL sorted_operation_ids)
    message(FATAL_ERROR "Pruning operations are not sorted")
endif()

set(forbidden_inputs
    "qgetenv("
    "getenv("
    "std::chrono"
    "steady_clock"
    "wall_clock"
    "wall clock"
    "telemetry"
    "lagrangian")
foreach(source IN LISTS actual_sources)
    file(READ "${source_root}/${source}" content)
    string(TOLOWER "${content}" lower_content)
    foreach(input IN LISTS forbidden_inputs)
        string(FIND "${lower_content}" "${input}" input_index)
        if(NOT input_index EQUAL -1)
            message(FATAL_ERROR "Forbidden pruning input '${input}' in ${source}")
        endif()
    endforeach()
    if(lower_content MATCHES "(^|[^a-z0-9_])eta([^a-z0-9_]|$)")
        message(FATAL_ERROR "ETA input found in ${source}")
    endif()
endforeach()

function(require_source_text path text)
    file(READ "${source_root}/${path}" source)
    string(FIND "${source}" "${text}" text_index)
    if(text_index EQUAL -1)
        message(FATAL_ERROR "Missing frozen predicate '${text}' in ${path}")
    endif()
endfunction()

require_source_text(ai/coordinator/bundleassignment.h "ASSIGNMENT_STATE_BUDGET = 200000")
require_source_text(ai/coordinator/bundleassignment.h "SETTLING_SWEEP_CAP = 8")
require_source_text(ai/coordinator/bundleassignment.h "SWAP_SWEEP_CAP = 4")
require_source_text(ai/coordinator/bundleassignment.h "CLUSTER_ACTOR_CAP = 6")
require_source_text(ai/coordinator/bundleassignment.h "CLUSTER_CANDIDATE_CAP = 12")
require_source_text(ai/coordinator/bundleassignment.h "CLUSTER_STATE_CAP = 20000")
require_source_text(ai/coordinator/bundleassignment.h "upper <= search.incumbentLower")
require_source_text(ai/coordinator/bundleassignment.h "SearchPricingMode::LegacyScalar")
require_source_text(ai/coordinator/propertystocksequential.h "SEQUENTIAL_SEARCH_STATE_CAP = 100000")
require_source_text(ai/coordinator/continuationinterval.h "LIVE_PAIR_RELEASE_BUDGET_NANOS = 300000000")
require_source_text(ai/coordinator/continuationinterval.h "LIVE_PAIR_STATE_TENTH_NANOS = 1395")
require_source_text(ai/coordinator/continuationinterval.h "LIVE_PAIR_DAY2_PACKING_STATES = 171992654")
require_source_text(ai/coordinator/continuationinterval.h "LIVE_PAIR_DAY2_SOLVES = 17900")
require_source_text(ai/coordinator/continuationinterval.h "LIVE_PAIR_REFINEMENT_BUDGET == 2150537")
require_source_text(ai/coordinator/continuationinterval.h "LIVE_PAIR_SLICE_BASE == 9609")

message(STATUS "${gate} passed for ${STAGE} with ${actual_count} sources")
