foreach(required DEBUG_ON RELEASE_ON RELEASE_OFF)
    if (NOT DEFINED ${required})
        message(FATAL_ERROR "${required} was not provided")
    endif()
endforeach()

set(debug_ninja "${DEBUG_ON}/build.ninja")
set(release_on_ninja "${RELEASE_ON}/build.ninja")
set(release_off_ninja "${RELEASE_OFF}/build.ninja")
foreach(build_file ${debug_ninja} ${release_on_ninja} ${release_off_ninja})
    if (NOT EXISTS "${build_file}")
        message(FATAL_ERROR "Missing build graph: ${build_file}")
    endif()
endforeach()

file(READ "${debug_ninja}" debug_graph)
file(READ "${release_on_ninja}" release_on_graph)
file(READ "${release_off_ninja}" release_off_graph)

foreach(on_graph debug_graph release_on_graph)
    string(FIND "${${on_graph}}" "tests/arena/arenatestsupport.cpp" support_index)
    if (support_index EQUAL -1)
        message(FATAL_ERROR "${on_graph} omits arenatestsupport.cpp")
    endif()
    string(FIND "${${on_graph}}" "coreengine/interpreter.cpp.obj" interpreter_index)
    if (interpreter_index EQUAL -1)
        message(FATAL_ERROR "${on_graph} omits interpreter.cpp")
    endif()
    string(SUBSTRING "${${on_graph}}" ${interpreter_index} 2000 interpreter_block)
    string(FIND "${interpreter_block}" "COW_AI_ARENA_TESTING" macro_index)
    if (macro_index EQUAL -1)
        message(FATAL_ERROR "${on_graph} omits the interpreter-only arena definition")
    endif()
    string(REGEX MATCHALL "COW_AI_ARENA_TESTING" macro_uses "${${on_graph}}")
    list(LENGTH macro_uses macro_count)
    if (NOT macro_count EQUAL 1)
        message(FATAL_ERROR "${on_graph} has ${macro_count} arena definition uses")
    endif()
endforeach()

string(FIND "${release_off_graph}" "tests/arena/" off_test_index)
if (NOT off_test_index EQUAL -1)
    message(FATAL_ERROR "Release OFF contains an arena test source")
endif()
string(FIND "${release_off_graph}" "COW_AI_ARENA_TESTING" off_macro_index)
if (NOT off_macro_index EQUAL -1)
    message(FATAL_ERROR "Release OFF contains COW_AI_ARENA_TESTING")
endif()

message(STATUS "ON/OFF source linkage audit passed")
